  config:
    environment:
      CONFIG_SERVICE_PASSWORD: config001
    image: aki59tiwari/petcare-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: config001
    image: aki59tiwari/petcare-config
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"