security:
  oauth2:
  resource:
    userInfoUri: BUGFIX
    client:
      clientId: inventory-service
      clientSecret: inventory001
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
      
    