security:
  oauth2:
    client:
      clientId: inventory-service
      clientSecret: inventory001
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:5000/uaa/user/current
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petCare_inventory
    username: akash
    password: petCare001
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 9000
  

          
    